/* -*- Mode: C++; tab-width: 2; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
/* vim: set sw=2 ts=2 et ft=cpp : */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"

interface NetworkTestListener;

[scriptable, uuid(acd7dbad-38b1-4194-a907-faa1b8593f16)]
interface NetworkTest : nsISupports
{
  void runTest(in NetworkTestListener aListener);
};

[scriptable, uuid(22d0d3e9-606b-4135-81e2-b589ffc96eb7)]
interface NetworkTestListener : nsISupports
{
  void testsFinished();
};

%{C++

#define NETWORKTEST_CONTRACTID                      \
  "@mozilla.org/network-test;1"
#define NETWORKTEST_CID                             \
{                                                   \
  0xacd7dbad,                                       \
  0x38b1,                                           \
  0x4194,                                           \
  {0xa9, 0x07, 0xfa, 0xa1, 0xb8, 0x59, 0x3f, 0x16}  \
}

%}
